_common: !include "../../common.yaml"
name: pinafore-gnome
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - polar-shim
      - typed-expression
      - Color
      - gi-cairo-render
      - gi-gio
      - gi-gdk
      - gi-gtk
      - changes-core
      - changes-world
      - changes-media
      - changes-gnome
      - pinafore-base
      - pinafore-language
      - pinafore-media
    exposed-modules:
      - Pinafore.Language.Library.GTK
    other-modules:
      - Pinafore.Language.Library.GIO
      - Pinafore.Language.Library.GTK.Context
      - Pinafore.Language.Library.GTK.Element.Context
      - Pinafore.Language.Library.GTK.Element.Drawing
      - Pinafore.Language.Library.GTK.Element
      - Pinafore.Language.Library.GTK.MenuItem
      - Pinafore.Language.Library.GTK.Window
      - Pinafore.Language.Library.GTK.Debug

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - filepath
          - gi-gtk
          - gi-gobject
          - haskell-gi-base
          - changes-core
          - changes-gnome
          - pinafore-language
          - pinafore-gnome
        main: Main.hs
        other-modules:
          - Test.Context
          - Test.GTK
          - Test.UI
        ghc-options: -threaded
