_common: !include "../../common.yaml"
name: pinafore-gnome
version: *pinafore_version
<<: *author

<<: *language

flags:
    test-X11:
        description: Run tests that require an X11 server
        default: true
        manual: false

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - shapes
      - time
      - polar-shim
      - typed-expression
      - Color
      - gi-cairo-render
      - gi-gio
      - gi-gdk
      - gi-gtk
      - gi-webkit2
      - thread-trace
      - changes-core
      - changes-world
      - changes-media
      - changes-gnome
      - pinafore-language
      - pinafore-media
    exposed-modules:
      - Pinafore.Language.Library.GNOME
    other-modules:
      - Pinafore.Language.Library.GIO
      - Pinafore.Language.Library.GTK.Context
      - Pinafore.Language.Library.GTK.Widget.Context
      - Pinafore.Language.Library.GTK.Widget.Drawing
      - Pinafore.Language.Library.GTK.Widget
      - Pinafore.Language.Library.GTK.MenuEntry
      - Pinafore.Language.Library.GTK.Clipboard
      - Pinafore.Language.Library.GTK.Window
      - Pinafore.Language.Library.GTK.Debug
      - Pinafore.Language.Library.GTK
      - Pinafore.Language.Library.WebKit

tests:
    test:
        source-dirs: test
        when:
          - condition: flag(test-X11)
            cpp-options: -DTEST_X11
        dependencies:
          - base >= 4.16
          - shapes
          - filepath
          - gi-gtk
          - gi-gobject
          - haskell-gi-base
          - thread-trace
          - changes-core
          - changes-gnome
          - pinafore-language
          - pinafore-gnome
        main: Main.hs
        other-modules:
          - Flags
          - Test.Context
          - Test.Golden
          - Test.UI
        ghc-options: -threaded
