_common: !include "../../common.yaml"
name: pinafore-lib-media
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - shapes
      - base64
      - commonmark
      - commonmark-extensions
      - Color
      - network-uri
      - cairo-functional
      - changes-world
      - changes-media
      - polar-shim
      - pinafore-language
    exposed-modules:
      - Pinafore.Library.Media
    other-modules:
      - Pinafore.Library.Media.Media
      - Pinafore.Library.Media.URI
      - Pinafore.Library.Media.HTML
      - Pinafore.Library.Media.CSS
      - Pinafore.Library.Media.CommonMark
      - Pinafore.Library.Media.Colour
      - Pinafore.Library.Media.Image.Metadata
      - Pinafore.Library.Media.Image.Image
      - Pinafore.Library.Media.Image.PNG
      - Pinafore.Library.Media.Image.JPEG
      - Pinafore.Library.Media.Image
      - Pinafore.Library.Media.Cairo

tests:
    test:
        source-dirs: test
        dependencies:
          - shapes
          - filepath
          - thread-trace
          - changes-core
          - changes-gnome
          - pinafore-language
          - pinafore-lib-media
        main: Main.hs
        other-modules:
          - Test.Golden
        ghc-options: -threaded
