_common: !include "../../common.yaml"
name: changes-gnome
version: *changes_version
<<: *author

<<: *language

flags:
    build-examples:
        description: Build examples
        default: false
        manual: false
    trace:
        description: Trace functions
        default: true
        manual: false
    test-X11:
        description: Run tests that require an X11 server
        default: true
        manual: false

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - time
      - vector
      - haskell-gi-base
      - gi-glib
      - gi-gio
      - gi-gobject
      - gi-gdk
      - gi-gdkpixbuf
      - gi-cairo-connector
      - gi-pango
      - gi-gtk
      - gi-gtk-hs
      - gi-webkit2
      - thread-trace
      - shapes
      - cairo-functional
      - changes-core
      - changes-media
    exposed-modules:
      - Changes.World.GNOME.GIO
      - Changes.World.GNOME.GTK
      - Changes.World.GNOME.GTK.Test
    when:
      - condition: flag(trace)
        exposed-modules:
          - Changes.World.GNOME.GI.Trace
    other-modules:
      - Changes.World.GNOME.GI.Error
      - Changes.World.GNOME.GI.Type
      - Changes.World.GNOME.GI.ViewLock
      - Changes.World.GNOME.GI.LockState
      - Changes.World.GNOME.GI.GView
      - Changes.World.GNOME.GI.Lifecycle
      - Changes.World.GNOME.GI.Signal
      - Changes.World.GNOME.GI.Widget
      - Changes.World.GNOME.GI
      - Changes.World.GNOME.GTK.Widget.TextStyle
      - Changes.World.GNOME.GTK.Widget.DynamicStore
      - Changes.World.GNOME.GTK.Widget.Blank
      - Changes.World.GNOME.GTK.Widget.Cairo
      - Changes.World.GNOME.GTK.Widget.CSS
      - Changes.World.GNOME.GTK.Widget.Button
      - Changes.World.GNOME.GTK.Widget.Image
      - Changes.World.GNOME.GTK.Widget.Icon
      - Changes.World.GNOME.GTK.Widget.Label
      - Changes.World.GNOME.GTK.Widget.Maybe
      - Changes.World.GNOME.GTK.Widget.ListBox
      - Changes.World.GNOME.GTK.Widget.Switch
      - Changes.World.GNOME.GTK.Widget.CheckButton
      - Changes.World.GNOME.GTK.Widget.Option
      - Changes.World.GNOME.GTK.Widget.TextEntry
      - Changes.World.GNOME.GTK.Widget.Text
      - Changes.World.GNOME.GTK.Widget.Layout
      - Changes.World.GNOME.GTK.Widget.Notebook
      - Changes.World.GNOME.GTK.Widget.Table
      - Changes.World.GNOME.GTK.Widget.Drag
      - Changes.World.GNOME.GTK.Widget.MenuBar
      - Changes.World.GNOME.GTK.Widget.Scrolled
      - Changes.World.GNOME.GTK.Widget.Calendar
      - Changes.World.GNOME.GTK.Widget.WebView
      - Changes.World.GNOME.GTK.ChooseFile
      - Changes.World.GNOME.GTK.Clipboard
      - Changes.World.GNOME.GTK.Window
      - Changes.World.GNOME.GTK.Main

tests:
    test:
        source-dirs: test
        when:
          - condition: flag(test-X11)
            cpp-options: -DTEST_X11
        dependencies:
          - base >= 4.16
          - shapes
          - changes-core
          - changes-gnome
          - gi-gio
          - gi-cairo-render
        main: Main.hs
        other-modules:
          - Flags
          - Matrix
          - Lock
          - GIO
        ghc-options: -threaded

executables:
    changes-text:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/text
        dependencies:
          - base >= 4.16
          - filepath
          - bytestring
          - thread-trace
          - shapes
          - changes-core
          - changes-gnome
          - changes-world
          - optparse-applicative
        main: Main.hs
        ghc-options: -threaded
    changes-gio:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/gio
        dependencies:
          - base >= 4.16
          - filepath
          - bytestring
          - gi-gio
          - uuid
          - aeson
          - shapes
          - changes-core
          - changes-gnome
          - changes-world
          - optparse-applicative
        main: Main.hs
        ghc-options: -threaded
    changes-soup:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/soup
        dependencies:
          - base >= 4.16
          - filepath
          - bytestring
          - uuid
          - aeson
          - shapes
          - changes-core
          - changes-gnome
          - changes-world
          - optparse-applicative
        main: Main.hs
        other-modules:
          - Soup
          - Soup.Note
          - Soup.Edit
          - Soup.UI
        ghc-options: -threaded
    changes-showImages:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/showImages
        dependencies:
          - base >= 4.16
          - filepath
          - directory
          - shapes
          - changes-core
          - changes-media
          - changes-world
          - changes-gnome
        main: Main.hs
        ghc-options: -threaded
    changes-cairo:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/cairo
        dependencies:
          - base >= 4.16
          - shapes
          - time
          - cairo-functional
          - changes-core
          - changes-world
          - changes-gnome
          - gi-cairo-render
          - gi-gtk
        main: Main.hs
        ghc-options: -threaded
