packages:
- shapes
- truth-core
- truth-gtk
- pinafore
- location:
    git: git@github.com:AshleyYakeley/hindent.git
    commit: 858d05a8e92b092e5dd1d2b88c25272dfb092333
  extra-dep: true

resolver: lts-9.10

extra-deps:
- directory-1.3.1.1
- mime-0.4.0.2
- haskell-src-exts-1.19.1

flags:
    truth-gtk:
        build-examples: true
