packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-9.21

extra-deps:
- directory-1.3.1.1
- mime-0.4.0.2
- haskell-src-exts-1.20.1
- git: git@github.com:AshleyYakeley/hindent.git
  commit: f20a764f40bc68fa5ada1dd38318be936219fbd8

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
