packages:

# separate (submodule) dependencies
- external/countable
- external/witness
- external/open-witness

# Changes
- Changes/monadology
- Changes/shapes
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gtk

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-language
- Pinafore/pinafore-gtk
- Pinafore/pinafore-app

resolver: lts-19.0

allow-newer: true

extra-deps:
- mime-0.4.0.2
- gi-cairo-render-0.1.0
- gi-cairo-connector-0.1.0
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 0f5103dd6fbea4f7ee8b156b40c7782e989e7025
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 9023e5da7245a802fa115a5e616f8beca0c9ffcf
- git: https://github.com/AshleyYakeley/licensor.git
  commit: cecb4e7a9be09f61ad748b837cf702bbd4a0c0c2
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
#- blaze-textual-0.2.2.1
#- sqlite-simple-0.4.18.0
#- gi-gdk-3.0.24
#- gi-gtk-3.0.37
#- gi-gtk-hs-0.3.10

flags:
    changes-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
