packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-12.2

extra-deps:
- mime-0.4.0.2
- git: git@github.com:AshleyYakeley/hindent.git
  commit: 5f8f95de55a524ed0b812ba6827550a29f4e02df

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
