packages:
- witness
- open-witness
- transformers-extra
- shapes
- typed-expression
- truth-core
- truth-world
- truth-gtk
- pinafore-base
- pinafore

resolver: lts-14.14

allow-newer: true

extra-deps:
- mime-0.4.0.2
- haskell-src-exts-1.22.0
- git: https://github.com/AshleyYakeley/hindent.git
  commit: d07e0ab032f9766f2d92dc260497ebd1ffbe62d7
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
