packages:

# examination
#- examine/gnome-bindings

# separate (submodule) dependencies
#- external/countable
- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology
- external/primitive-serial

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-language
- Pinafore/pinafore-media
- Pinafore/pinafore-gnome
- Pinafore/pinafore-app

resolver: nightly-2023-05-10

allow-newer: true

extra-deps:
- blake3-0.2
- leb128-0.1.0.0
- git: https://github.com/AshleyYakeley/haskell-gi.git
  commit: db5ec051116579c33472a0193251a3333f3f336f
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 9dff0f37cb7cc00129f65c85aa9a820c579472ca
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 7faad14a228fb5b52e233ebd23ea92beafe2cd8d
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

nix:
    enable: false
    path:
    # https://github.com/NixOS/nixpkgs/tags
    - nixpkgs=https://github.com/nixos/nixpkgs/tarball/22.11
    packages:
    - zlib
    - pkg-config
    - gobject-introspection
    - cairo
    - gdk-pixbuf
    - harfbuzz
    - atkmm
    - pango
    - gtk3

ghc-options:
    "$locals": -Werror
