packages:

# examination
#- examine/gnome-bindings

# separate (submodule) dependencies
#- external/countable
#- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology
#- external/primitive-serial

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-syntax
- Pinafore/pinafore-language
- Pinafore/pinafore-lib-media
- Pinafore/pinafore-lib-gnome
- Pinafore/pinafore-lib-script
- Pinafore/pinafore-app
- Pinafore/pinafore-docgen

resolver: lts-23.0

allow-newer: true

extra-deps:
- gi-javascriptcore-4.0.28
- gi-webkit2-4.0.31
- blake3-0.3
- leb128-0.1.0.0
- optparse-applicative-0.17.1.0
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 443776e416f3fc3c2b56cbd5b11beaf022365c9d
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 39739ea7717249e405ab67c8a579b552e4cec8b9
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
- witness-0.7
- monadology-0.4
- open-witness-0.7

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

notify-if-nix-on-path: false

nix:
    enable: false
    path:
    # https://github.com/NixOS/nixpkgs/tags
    - nixpkgs=https://github.com/nixos/nixpkgs/tarball/23.05
    packages:
    - zlib
    - pkg-config
    - gobject-introspection
    - cairo
    - gdk-pixbuf
    - harfbuzz
    - atkmm
    - libthai
    - libdatrie
    - libxkbcommon
    - libepoxy
    - pango
    - pcre
    - pcre2
    - xorg.libXdmcp
    - xorg.libXtst
    - util-linux
    - libselinux
    - libsepol
    - gtk3

ghc-options:
    "$locals": -Werror
