packages:

# examination
#- examine/gnome-bindings

# separate (submodule) dependencies
- external/countable
- external/witness
#- external/open-witness
#- external/type-rig
- external/monadology
#- external/primitive-serial

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-storage
- Pinafore/pinafore-syntax
- Pinafore/pinafore-language
- Pinafore/pinafore-lib-media
- Pinafore/pinafore-lib-gnome
- Pinafore/pinafore-lib-script
- Pinafore/pinafore-app
- Pinafore/pinafore-docgen

resolver: lts-24.6

allow-newer: true
allow-newer-deps:
    - leb128
    - optparse-applicative
    - criterion
    - fourmolu

extra-deps:
# GTK
- haskell-gi-0.26.14
- haskell-gi-base-0.26.8
- gi-glib-2.0.30
- gi-gio-2.0.35
- gi-gdk-3.0.29
- gi-gtk-3.0.43
- gi-gtk-hs-0.3.17
- gi-soup-2.4.29
- gi-javascriptcore-4.0.28
- gi-webkit2-4.0.31

# other
- blake3-0.3
- leb128-0.1.0.0
- optparse-applicative-0.17.1.0

# format
- Cabal-syntax-3.12.1.0
- Cabal-3.12.1.0
- ghc-lib-parser-9.10.2.20250515
- github: AshleyYakeley/fourmolu
  commit: 8f7bfbaebfc7337e3301f87ba602fea65ad12323

# my stuff
#- witness-0.8
- open-witness-0.7

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

notify-if-nix-on-path: false
recommend-stack-upgrade: false

nix:
    enable: false

ghc-options:
    "$locals": -Werror
