packages:

# examination
#- examine/gnome-bindings

# separate (submodule) dependencies
#- external/countable
#- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology
#- external/primitive-serial

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-syntax
- Pinafore/pinafore-language
- Pinafore/pinafore-lib-media
- Pinafore/pinafore-lib-gnome
- Pinafore/pinafore-lib-script
- Pinafore/pinafore-app
- Pinafore/pinafore-docgen

resolver: lts-23.5

allow-newer: true
allow-newer-deps:
    - leb128
    - optparse-applicative
    - criterion

extra-deps:
# GTK
- gi-gdk-4.0.9
- gi-gsk-4.0.8
- gi-gtk-4.0.9
- gi-soup-3.0.3
- gi-javascriptcore-6.0.4
- gi-webkit-6.0.3

# other
- blake3-0.3
- leb128-0.1.0.0
- optparse-applicative-0.17.1.0

# format
- Cabal-syntax-3.12.1.0
- Cabal-3.12.1.0
- ghc-lib-parser-9.10.1.20250103
- github: AshleyYakeley/fourmolu
  commit: 8f7bfbaebfc7337e3301f87ba602fea65ad12323

# my stuff
- witness-0.7
- monadology-0.4
- open-witness-0.7

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

notify-if-nix-on-path: false

nix:
    enable: false
    path:
    # https://github.com/NixOS/nixpkgs/tags
    - nixpkgs=https://github.com/nixos/nixpkgs/tarball/23.05
    packages:
    - zlib
    - pkg-config
    - gobject-introspection
    - cairo
    - gdk-pixbuf
    - harfbuzz
    - atkmm
    - libthai
    - libdatrie
    - libxkbcommon
    - libepoxy
    - pango
    - pcre
    - pcre2
    - xorg.libXdmcp
    - xorg.libXtst
    - util-linux
    - libselinux
    - libsepol
    - gtk3

ghc-options:
    "$locals": -Werror
