packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-13.12

allow-newer: true

extra-deps:
- time-1.9.2
- mime-0.4.0.2
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 95ee87832d24a155031dbcd87a447521f745316a
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 35efac338e80c56a2065d7db4f09ecbe2e97bc7e
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
