packages:

# separate (submodule) dependencies
#- external/countable
- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-language
- Pinafore/pinafore-media
- Pinafore/pinafore-gnome
- Pinafore/pinafore-app

resolver: lts-19.22

allow-newer: true

extra-deps:
- invariant-0.6
- blake3-0.2
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: a2225286fa8349de93b4c0ccc85b8cae8c5d8d05
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 79666871c61c2846c1ec1f7b33c8ebe04546ef73
- git: https://github.com/AshleyYakeley/licensor.git
  commit: cecb4e7a9be09f61ad748b837cf702bbd4a0c0c2
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14
- countable-1.2
- open-witness-0.6
- type-rig-0.1
- monadology-0.1

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
