packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-12.2

extra-deps:
- mime-0.4.0.2
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: eb9e6bfd89b2a97fb9ac52d967465f62d2c6ed64
- git: https://github.com/AshleyYakeley/hindent.git
  commit: f89706053516ae182f247e4c23795cd8447810d5

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
