packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-12.22

extra-deps:
- mime-0.4.0.2
- haskell-src-exts-1.21.0
- git: https://github.com/AshleyYakeley/hindent.git
  commit: ca4d121c29b20cbf10ab3e8ee4d1773119d0492d
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
