packages:

# examination
#- examine/gnome-bindings

# separate (submodule) dependencies
#- external/countable
#- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology
#- external/primitive-serial

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-language
- Pinafore/pinafore-media
- Pinafore/pinafore-gnome
- Pinafore/pinafore-stdlib
- Pinafore/pinafore-app

resolver: lts-22.7

allow-newer: true

extra-deps:
- blake3-0.3
- leb128-0.1.0.0
- gi-cairo-connector-0.1.1
- optparse-applicative-0.17.1.0
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 9dff0f37cb7cc00129f65c85aa9a820c579472ca
- git: https://github.com/AshleyYakeley/hindent.git
  commit: b993de547755ead487b3285c3cd09bebe584c73b
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

nix:
    enable: false
    path:
    # https://github.com/NixOS/nixpkgs/tags
    - nixpkgs=https://github.com/nixos/nixpkgs/tarball/23.05
    packages:
    - zlib
    - pkg-config
    - gobject-introspection
    - cairo
    - gdk-pixbuf
    - harfbuzz
    - atkmm
    - libthai
    - libdatrie
    - libxkbcommon
    - libepoxy
    - pango
    - pcre
    - pcre2
    - xorg.libXdmcp
    - xorg.libXtst
    - util-linux
    - libselinux
    - libsepol
    - gtk3

ghc-options:
    "$locals": -Werror
