packages:

# separate (submodule) dependencies
- witness
- open-witness

# Changes
- transformers-extra
- shapes
- changes-core
- changes-media
- changes-world
- changes-gtk

# Pinafore
- typed-expression
- pinafore-base
- pinafore-language
- pinafore-gtk
- pinafore-app

resolver: lts-17.0

allow-newer: true

extra-deps:
- mime-0.4.0.2
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: 0f5103dd6fbea4f7ee8b156b40c7782e989e7025
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 9023e5da7245a802fa115a5e616f8beca0c9ffcf
- git: https://github.com/AshleyYakeley/licensor.git
  commit: cecb4e7a9be09f61ad748b837cf702bbd4a0c0c2
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    changes-gtk:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
