packages:

# separate (submodule) dependencies
#- external/countable
- external/witness
#- external/open-witness
#- external/type-rig
#- external/monadology

# Changes
- Changes/thread-trace
- Changes/shapes
- Changes/cairo-functional
- Changes/changes-core
- Changes/changes-media
- Changes/changes-world
- Changes/changes-gnome

# Pinafore
- Pinafore/polar-shim
- Pinafore/typed-expression
- Pinafore/pinafore-base
- Pinafore/pinafore-language
- Pinafore/pinafore-media
- Pinafore/pinafore-gnome
- Pinafore/pinafore-app

resolver: lts-20.4

allow-newer: true

extra-deps:
- blake3-0.2
- git: https://github.com/AshleyYakeley/haskell-src-exts.git
  commit: d1a86659a8c5d9526b9b23b6ba9538f5aed2e4a7
- git: https://github.com/AshleyYakeley/hindent.git
  commit: 1a12acd42e1da0a419d47225581a179b3a24f53b
- git: https://github.com/AshleyYakeley/licensor.git
  commit: cecb4e7a9be09f61ad748b837cf702bbd4a0c0c2
- git: https://github.com/fpco/ghc-prof-flamegraph.git
  commit: 8edd3b4806adeb25a4d55bed51c3afcc8e7a8e14

flags:
    changes-gnome:
        build-examples: true

docker:
    enable: true
    image: "local-build"

ghc-options:
    "$locals": -Werror
