packages:
- witness
- open-witness
- transformers-extra
- shapes
- truth-core
- truth-gtk
- pinafore

resolver: lts-9.12

extra-deps:
- directory-1.3.1.1
- mime-0.4.0.2
- haskell-src-exts-1.20.1
- gi-gtk-hs-0.3.5.0
- git: git@github.com:AshleyYakeley/hindent.git
  commit: 82412270de10544cd37ca70ea82ecb688dcb6aec

flags:
    truth-gtk:
        build-examples: true

docker:
    enable: true
    auto-pull: true
