packages:
- shapes
- truth-core
- truth-gtk
- pinafore
- location:
    git: git@github.com:AshleyYakeley/hindent.git
    commit: faf7dbc3100c46af8c49fdeb7f7d3e82c95442a2
  extra-dep: true

resolver: lts-9.10

extra-deps:
- directory-1.3.1.1
- mime-0.4.0.2
- haskell-src-exts-1.19.1

flags:
    truth-gtk:
        build-examples: true
