_common: !include "../../common.yaml"
name: cairo-functional
version: *changes_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - bytestring-to-vector
      - JuicyPixels
      - gi-cairo-render
      - shapes
    exposed-modules:
      - Graphics.Cairo.Functional
      - Graphics.Cairo.Image
