_common: !include "../../common.yaml"
name: polar-shim
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - shapes
      - thread-trace
    exposed-modules:
      - Data.Shim
    other-modules:
      - Data.Shim.Polar.Polarity
      - Data.Shim.Polar.JoinMeet
      - Data.Shim.Polar.MPolarity
      - Data.Shim.Polar
      - Data.Shim.Mono.General
      - Data.Shim.Mono.Compose
      - Data.Shim.Mono.Polar
      - Data.Shim.Mono.Variance
      - Data.Shim.Mono.ShimWit
      - Data.Shim.Mono.PolarShimWit
      - Data.Shim.Mono.PolarJoinMeet
      - Data.Shim.Mono.PShimWit
      - Data.Shim.Mono.Arguments
      - Data.Shim.Mono.Retract
      - Data.Shim.Mono
      - Data.Shim.Poly.Shim
      - Data.Shim.Poly.Map
      - Data.Shim.Poly.Identity
      - Data.Shim.Poly.Neutral
      - Data.Shim.Poly.Dual
      - Data.Shim.Poly.Iso
      - Data.Shim.Poly.Compose
      - Data.Shim.Poly.Null
      - Data.Shim.Poly
      - Data.Shim.Range.Range
      - Data.Shim.Range.RangeType
      - Data.Shim.Range.CatRange
      - Data.Shim.Range
      - Data.Shim.CCR.PolarVariance
      - Data.Shim.CCR.JMPolyShim
      - Data.Shim.CCR.JMPolyShimWit
      - Data.Shim.CCR.Variance
      - Data.Shim.CCR.Covariance
      - Data.Shim.CCR.Variances
      - Data.Shim.CCR.Apply
      - Data.Shim.CCR.Argument
      - Data.Shim.CCR.Arguments
      - Data.Shim.CCR

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - shapes
          - polar-shim
        main: Main.hs
        ghc-options: -threaded
