_common: !include "../../common.yaml"
name: pinafore-language
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - filepath
      - directory
      - parsec
      - containers
      - text
      - unicode-collation
      - polar-shim
      - typed-expression
      - changes-core
      - changes-world
      - pinafore-base
    exposed-modules:
      - Pinafore.Language
      - Pinafore.Language.API
      - Pinafore.Documentation
      - Pinafore.Main
      - Pinafore
      - Pinafore.Test
    other-modules:
      - Pinafore.Markdown
      - Pinafore.Context
      - Pinafore.Language.Value.Instances
      - Pinafore.Language.Value.WholeRef
      - Pinafore.Language.Value.SetRef
      - Pinafore.Language.Value.FiniteSetRef
      - Pinafore.Language.Value.ListRef
      - Pinafore.Language.Value.TextRef
      - Pinafore.Language.Value.Morphism
      - Pinafore.Language.Value.RefOrder
      - Pinafore.Language.Value
      - Pinafore.Language.Name
      - Pinafore.Language.Shim
      - Pinafore.Language.If
      - Pinafore.Language.Type.Family
      - Pinafore.Language.Type.Show
      - Pinafore.Language.Type.Ground
      - Pinafore.Language.Type.Types
      - Pinafore.Language.Type.Identified
      - Pinafore.Language.Error
      - Pinafore.Language.SpecialForm
      - Pinafore.Language.VarID
      - Pinafore.Language.Interpreter
      - Pinafore.Language.Var
      - Pinafore.Language.Convert.HasType
      - Pinafore.Language.Convert.Types
      - Pinafore.Language.Convert
      - Pinafore.Language.ExprShow
      - Pinafore.Language.Type.Type
      - Pinafore.Language.Type.GetDynamicSupertype
      - Pinafore.Language.Type.Subtype
      - Pinafore.Language.Type.Entity.Type
      - Pinafore.Language.Type.Entity.Dynamic
      - Pinafore.Language.Type.Entity.Closed
      - Pinafore.Language.Type.Entity.Open
      - Pinafore.Language.Type.Entity
      - Pinafore.Language.Type.DynamicSupertype
      - Pinafore.Language.Type
      - Pinafore.Language.DefDoc
      - Pinafore.Language.Grammar.Syntax
      - Pinafore.Language.Grammar.Read.Token
      - Pinafore.Language.Grammar.Read.Parser
      - Pinafore.Language.Grammar.Read.Type
      - Pinafore.Language.Grammar.Read.TypeDecls
      - Pinafore.Language.Grammar.Read.Infix
      - Pinafore.Language.Grammar.Read.Constructor
      - Pinafore.Language.Grammar.Read.Pattern
      - Pinafore.Language.Grammar.Read.Expression
      - Pinafore.Language.Grammar.Read.Interactive
      - Pinafore.Language.Grammar.Read
      - Pinafore.Language.Grammar.Interpret.RefNotation
      - Pinafore.Language.Grammar.Interpret.ScopeBuilder
      - Pinafore.Language.Grammar.Interpret.Type
      - Pinafore.Language.Grammar.Interpret.TypeDecl.TypeBox
      - Pinafore.Language.Grammar.Interpret.TypeDecl.Mapping
      - Pinafore.Language.Grammar.Interpret.TypeDecl.Representation
      - Pinafore.Language.Grammar.Interpret.TypeDecl.Parameter
      - Pinafore.Language.Grammar.Interpret.TypeDecl.Data
      - Pinafore.Language.Grammar.Interpret.TypeDecl.ClosedEntity
      - Pinafore.Language.Grammar.Interpret.TypeDecl.OpenEntity
      - Pinafore.Language.Grammar.Interpret.TypeDecl.DynamicEntity
      - Pinafore.Language.Grammar.Interpret.TypeDecl
      - Pinafore.Language.Grammar.Interpret
      - Pinafore.Language.Grammar
      - Pinafore.Language.Expression
      - Pinafore.Language.DocTree
      - Pinafore.Language.Library.FetchModule
      - Pinafore.Language.Library.Defs
      - Pinafore.Language.Library.Std.Convert
      - Pinafore.Language.Library.Std.Base
      - Pinafore.Language.Library.Std.Reference
      - Pinafore.Language.Library.Std.File
      - Pinafore.Language.Library.Std
      - Pinafore.Language.Library.Debug
      - Pinafore.Language.Library

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - filepath
          - polar-shim
          - typed-expression
          - changes-core
          - pinafore-language
        main: Main.hs
        other-modules:
          - Test.RunScript
          - Test.Language
          - Test.Unifier
          - Test.Entity
          - Test.Type
          - Test.ReadType
          - Test.Output
          - Test.Module
          - Test.Interactive
        ghc-options: -threaded -rtsopts
