_common: !include "../../common.yaml"
name: pinafore-language
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - shapes
      - time
      - filepath
      - directory
      - containers
      - text
      - unicode-collation
      - thread-trace
      - polar-shim
      - typed-expression
      - changes-core
      - changes-world
      - pinafore-base
      - pinafore-syntax
    exposed-modules:
      - Pinafore.API
      - Pinafore.Documentation
      - Pinafore.Main
      - Pinafore.Test
      - Pinafore.Test.Internal
    other-modules:
      - Import
      - Pinafore.Context
      - Pinafore.Language.Debug
      - Pinafore.Language.Value.Instances
      - Pinafore.Language.Value.Map
      - Pinafore.Language.Value.Lens
      - Pinafore.Language.Value.Prism
      - Pinafore.Language.Value.Model
      - Pinafore.Language.Value.WholeModel
      - Pinafore.Language.Value.SetModel
      - Pinafore.Language.Value.FiniteSetModel
      - Pinafore.Language.Value.ListModel
      - Pinafore.Language.Value.TextModel
      - Pinafore.Language.Value.Attribute
      - Pinafore.Language.Value.Property
      - Pinafore.Language.Value.ModelOrder
      - Pinafore.Language.Value
      - Pinafore.Language.Shim
      - Pinafore.Language.If
      - Pinafore.Language.Type.Family
      - Pinafore.Language.Type.Show
      - Pinafore.Language.Type.Ground
      - Pinafore.Language.Type.Types
      - Pinafore.Language.Type.Identified
      - Pinafore.Language.Error
      - Pinafore.Language.SpecialForm
      - Pinafore.Language.VarID
      - Pinafore.Language.Interpreter.Binding
      - Pinafore.Language.Interpreter.Scope
      - Pinafore.Language.Interpreter.Interpreter
      - Pinafore.Language.Interpreter.Lookup
      - Pinafore.Language.Interpreter.ScopeDocs
      - Pinafore.Language.Interpreter.ScopeBuilder
      - Pinafore.Language.Interpreter.Register
      - Pinafore.Language.Interpreter
      - Pinafore.Language.Var
      - Pinafore.Language.Convert.HasType
      - Pinafore.Language.Convert.Types
      - Pinafore.Language.Convert
      - Pinafore.Language.Type.GetDynamicSupertype
      - Pinafore.Language.Type.Subtype.Hint
      - Pinafore.Language.Type.Subtype
      - Pinafore.Language.Type.Storable.Type
      - Pinafore.Language.Type.Storable.Dynamic.Entity
      - Pinafore.Language.Type.Storable.Dynamic.Storability
      - Pinafore.Language.Type.Storable.Dynamic.DynamicEntity
      - Pinafore.Language.Type.Storable.Dynamic.Concrete
      - Pinafore.Language.Type.Storable.Dynamic.Abstract
      - Pinafore.Language.Type.Storable.Dynamic
      - Pinafore.Language.Type.Storable.Open
      - Pinafore.Language.Type.Storable
      - Pinafore.Language.Type.DynamicSupertype
      - Pinafore.Language.Type
      - Pinafore.Language.Interpret.FreeVars
      - Pinafore.Language.Interpret.AppNotation
      - Pinafore.Language.Interpret.Type
      - Pinafore.Language.Interpret.TypeDecl.Representation
      - Pinafore.Language.Interpret.TypeDecl.Parameter
      - Pinafore.Language.Interpret.TypeDecl.Data
      - Pinafore.Language.Interpret.TypeDecl.StorableData
      - Pinafore.Language.Interpret.TypeDecl.OpenEntity
      - Pinafore.Language.Interpret.TypeDecl.DynamicEntity
      - Pinafore.Language.Interpret.TypeDecl
      - Pinafore.Language.Interpret.Expression
      - Pinafore.Language.Interpret.Interact
      - Pinafore.Language.Interpret
      - Pinafore.Language.Expression
      - Pinafore.Language.Library.FetchModule
      - Pinafore.Language.Library.Defs
      - Pinafore.Language.Library.Convert
      - Pinafore.Language.Library.Types
      - Pinafore.Language.Library.Base
      - Pinafore.Language.Library.Action
      - Pinafore.Language.Library.Lifecycle
      - Pinafore.Language.Library.Interpret
      - Pinafore.Language.Library.MIME
      - Pinafore.Language.Library.Model
      - Pinafore.Language.Library.Optics
      - Pinafore.Language.Library.ModelOrder
      - Pinafore.Language.Library.File
      - Pinafore.Language.Library.Task
      - Pinafore.Language.Library.Stream
      - Pinafore.Language.Library.Storage
      - Pinafore.Language.Library.Undo
      - Pinafore.Language.Library.Env
      - Pinafore.Language.Library.Eval
      - Pinafore.Language.Library.Debug
      - Pinafore.Language.Library
      - Pinafore.Language

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - shapes
          - filepath
          - thread-trace
          - polar-shim
          - typed-expression
          - changes-core
          - pinafore-language
        main: Main.hs
        other-modules:
          - Test.Markdown
          - Test.Name
          - Test.Token
          - Test.RunScript
          - Test.Language
          - Test.Solver
          - Test.Unifier
          - Test.Subtype
          - Test.Entity
          - Test.Type
          - Test.ReadType
          - Test.Output
          - Test.Namespace
          - Test.Module
          - Test.Interactive
        ghc-options: -threaded
