_common: !include "../common.yaml"
name: changes-media
version: *changes_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - shapes
      - deepseq
      - changes-core
      - JuicyPixels
    exposed-modules:
      - Data.Media.Image
      - Changes.Media.Image
    other-modules:
      - Data.Media.Image.Pixel
      - Data.Media.Image.Metadata
      - Data.Media.Image.JPEG
      - Data.Media.Image.True8
