name: truth-core
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - shapes
      - base >= 4.12
      - time
      - thread-trace
    exposed-modules:
      - Truth.Core
      - Truth.Debug
      - Truth.Debug.Edit
      - Truth.Debug.Object
      - Truth.Debug.Subscriber
    other-modules:
      - Truth.Core.Import
      - Truth.Core.Sequence
      - Truth.Core.Resource.Function
      - Truth.Core.Resource.SingleRunner
      - Truth.Core.Resource.ResourceRunner
      - Truth.Core.Resource.Runnable
      - Truth.Core.Resource
      - Truth.Core.Read.MutableRead
      - Truth.Core.Read.SubjectReader
      - Truth.Core.Read.FullSubjectReader
      - Truth.Core.Read
      - Truth.Core.Edit.Edit
      - Truth.Core.Edit.Update
      - Truth.Core.Edit.FullEdit
      - Truth.Core.Edit.Cache
      - Truth.Core.Edit.Function
      - Truth.Core.Edit.Lens
      - Truth.Core.Edit.Partial
      - Truth.Core.Edit.Opaque
      - Truth.Core.Edit
      - Truth.Core.Types.None
      - Truth.Core.Types.ReadOnly
      - Truth.Core.Types.Whole
      - Truth.Core.Types.WholeUpdateFunction
      - Truth.Core.Types.Unit
      - Truth.Core.Types.Sum
      - Truth.Core.Types.SumWhole
      - Truth.Core.Types.OneReader
      - Truth.Core.Types.OneEdit
      - Truth.Core.Types.OneWhole
      - Truth.Core.Types.Either
      - Truth.Core.Types.Comonad
      - Truth.Core.Types.Tuple
      - Truth.Core.Types.ConsTuple
      - Truth.Core.Types.EitherTuple
      - Truth.Core.Types.Pair
      - Truth.Core.Types.Lattice
      - Truth.Core.Types.Function
      - Truth.Core.Types.WholeFunction
      - Truth.Core.Types.Set
      - Truth.Core.Types.Dependent
      - Truth.Core.Types.Context
      - Truth.Core.Types.List
      - Truth.Core.Types.String
      - Truth.Core.Types.ByteString
      - Truth.Core.Types.Key
      - Truth.Core.Types.FiniteSet
      - Truth.Core.Types.Database
      - Truth.Core.Types.Database.Show
      - Truth.Core.Types.Database.Tuple
      - Truth.Core.Types.Database.Tuple.Show
      - Truth.Core.Types
      - Truth.Core.Object.DeferActionT
      - Truth.Core.Object.EditContext
      - Truth.Core.Object.Object
      - Truth.Core.Object.AutoClose
      - Truth.Core.Object.ObjectEdit
      - Truth.Core.Object.Update
      - Truth.Core.Object.ObjectMaker
      - Truth.Core.Object.Subscriber
      - Truth.Core.Object.Tuple
      - Truth.Core.Object.MemoryCell
      - Truth.Core.Object.Editor
      - Truth.Core.Object.Cache
      - Truth.Core.Object.Savable
      - Truth.Core.Object.Undo
      - Truth.Core.Object
      - Truth.Core.UI.Request
      - Truth.Core.UI.TextStyle
      - Truth.Core.UI.Specifier.Specifier
      - Truth.Core.UI.Specifier.Null
      - Truth.Core.UI.Specifier.Map
      - Truth.Core.UI.Specifier.Selection
      - Truth.Core.UI.Specifier.WithAspect
      - Truth.Core.UI.Specifier.CSS
      - Truth.Core.UI.Specifier.Button
      - Truth.Core.UI.Specifier.One
      - Truth.Core.UI.Specifier.Switch
      - Truth.Core.UI.Specifier.Layout
      - Truth.Core.UI.Specifier.Pages
      - Truth.Core.UI.Specifier.Icon
      - Truth.Core.UI.Specifier.Label
      - Truth.Core.UI.Specifier.Checkbox
      - Truth.Core.UI.Specifier.Option
      - Truth.Core.UI.Specifier.TextEntry
      - Truth.Core.UI.Specifier.TextEditor
      - Truth.Core.UI.Specifier.Table
      - Truth.Core.UI.Specifier.Drag
      - Truth.Core.UI.Specifier.MenuBar
      - Truth.Core.UI.Specifier.Scrolled
      - Truth.Core.UI.Specifier.Calendar
      - Truth.Core.UI.ViewContext
      - Truth.Core.UI.View
      - Truth.Core.UI.Window
      - Truth.Core.UI.Toolkit
      - Truth.Core.UI.CreateView
      - Truth.Core.UI.DynamicView
      - Truth.Core.UI.GetView
      - Truth.Core.UI

tests:
  test:
    source-dirs: test
    dependencies:
      - base >= 4.12
      - bytestring
      - containers
      - countable
      - open-witness
      - template-haskell
      - transformers
      - transformers-extra
      - witness
      - comonad
      - mono-traversable
      - shapes
      - truth-core
      - QuickCheck
      - tasty
      - tasty-expected-failure
      - tasty-hunit
      - tasty-quickcheck
      - tasty-golden
    main: Main.hs
    other-modules:
      - Test.SimpleString
      - Subscribe
    ghc-options: -threaded
