name: pinafore-base
version: "0.2"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - deepseq
      - time
      - cereal
      - memory
      - cryptonite
      - changes-core
      - changes-world
    exposed-modules:
      - Pinafore.Base
      - Pinafore.Storage
    other-modules:
      - Pinafore.Base.Know
      - Pinafore.Base.SafeRational
      - Pinafore.Base.Number
      - Pinafore.Base.Literal
      - Pinafore.Base.FunctionMorphism
      - Pinafore.Base.Morphism
      - Pinafore.Base.Ref
      - Pinafore.Base.Anchor
      - Pinafore.Base.Entity
      - Pinafore.Base.KnowShim
      - Pinafore.Base.EntityStorer
      - Pinafore.Base.Edit
      - Pinafore.Base.EntityAdapter
      - Pinafore.Base.PredicateMorphism
      - Pinafore.Base.Action
      - Pinafore.Base.ImmutableWholeRef
      - Pinafore.Base.File
      - Pinafore.Storage.Table
      - Pinafore.Storage.Database
      - Pinafore.Storage.Database.SQLite
      - Pinafore.Storage.File

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - changes-core
          - pinafore-base
        main: Main.hs
        other-modules:
          - Test.Numeric
          - Test.Anchor
          - Test.Storage
        ghc-options: -threaded
