name: pinafore-base
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - deepseq
      - time
      - cereal
      - memory
      - cryptonite
      - truth-core
      - truth-world
    exposed-modules:
      - Pinafore.Base
      - Pinafore.Storage
      - Pinafore.Pinafore
    other-modules:
      - Pinafore.Base.Know
      - Pinafore.Base.SafeRational
      - Pinafore.Base.Number
      - Pinafore.Base.Literal
      - Pinafore.Base.FunctionMorphism
      - Pinafore.Base.Morphism
      - Pinafore.Base.Ref
      - Pinafore.Base.Anchor
      - Pinafore.Base.Entity
      - Pinafore.Base.Lens
      - Pinafore.Base.Edit
      - Pinafore.Base.EntityAdapter
      - Pinafore.Base.PredicateMorphism
      - Pinafore.Base.Action
      - Pinafore.Base.Context
      - Pinafore.Base.ImmutableRef
      - Pinafore.Base.File
      - Pinafore.Storage.Table
      - Pinafore.Storage.Database
      - Pinafore.Storage.Database.SQLite
      - Pinafore.Storage.File

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - pinafore-base
          - tasty
          - tasty-hunit
        main: Main.hs
        other-modules:
          - Test.Numeric
          - Test.Anchor
        ghc-options: -threaded
