_common: !include "../../common.yaml"
name: pinafore-syntax
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base
      - open-witness
      - shapes
      - parsec
      - polar-shim
      - typed-expression
      - pinafore-base
    exposed-modules:
      - Pinafore.Syntax.Name
      - Pinafore.Syntax.Syntax
      - Pinafore.Syntax.Parse
      - Pinafore.Syntax.Doc
      - Pinafore.Syntax
    other-modules:
      - Pinafore.Syntax.Name.Name
      - Pinafore.Syntax.Name.ImplicitName
      - Pinafore.Syntax.Name.Namespace
      - Pinafore.Syntax.Name.FullName
      - Pinafore.Syntax.Name.NamespaceRef
      - Pinafore.Syntax.Name.FullNameRef
      - Pinafore.Syntax.Name.NamespaceConcat
      - Pinafore.Syntax.Name.ModuleName
      - Pinafore.Syntax.Name.NamedText
      - Pinafore.Syntax.Name.PrecNamedText
      - Pinafore.Syntax.Name.Show.Text
      - Pinafore.Syntax.Name.Show.NamedText
      - Pinafore.Syntax.Name.Show.Prec
      - Pinafore.Syntax.ReadShow
      - Pinafore.Syntax.Token
      - Pinafore.Syntax.Lex.Lexer
      - Pinafore.Syntax.Lex.Literal
      - Pinafore.Syntax.Lex
      - Pinafore.Syntax.Parse.Error
      - Pinafore.Syntax.Parse.Parser
      - Pinafore.Syntax.Parse.Basic
      - Pinafore.Syntax.Parse.Type
      - Pinafore.Syntax.Parse.Infix
      - Pinafore.Syntax.Parse.Constructor
      - Pinafore.Syntax.Parse.Pattern
      - Pinafore.Syntax.Parse.Expression
      - Pinafore.Syntax.Parse.Interactive
      - Pinafore.Syntax.Doc.DefDoc
      - Pinafore.Syntax.Doc.Docs
      - Pinafore.Syntax.Doc.SyntaxDoc

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - shapes
          - thread-trace
          - pinafore-base
          - pinafore-syntax
        main: Main.hs
        other-modules:
          - Test.ReadShow
        ghc-options: -threaded
