name: thread-trace
version: "0.1"
_common: !include "../../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      - base >= 4.16
      - time
      - containers
      - monadology
    exposed-modules:
      - Debug.Trace.Null
      - Debug.ThreadTrace
      - Debug.ThreadTrace.Lookup
