_common: !include "../common.yaml"
name: pinafore-app
version: *pinafore_version
<<: *author

<<: *language

extra-doc-files: examples/*

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - directory
      - filepath
      - xdg-basedir
      - githash
      - pinafore-language
      - pinafore-gtk
    exposed-modules:
      - Pinafore.Version
      - Pinafore.Options
      - Pinafore.Libs

executables:
    pinafore:
        source-dirs: app/main
        dependencies:
          - base >= 4.12
          - shapes
          - optparse-applicative
          - changes-core
          - changes-gtk
          - pinafore-language
          - pinafore-app
        main: Main.hs
        other-modules:
          - Options
          - Run
        ghc-options: -threaded
    pinafore-doc:
        source-dirs: app/doc
        dependencies:
          - base >= 4.12
          - shapes
          - filepath
          - optparse-applicative
          - pinafore-language
          - pinafore-app
        main: Main.hs
        other-modules:
          - Options
        ghc-options: -threaded

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - filepath
          - directory
          - shapes
          - changes-core
          - pinafore-language
          - pinafore-gtk
          - pinafore-app
        main: Main.hs
        other-modules:
          - Test.Interactive
          - Test.Scripts
        ghc-options: -threaded
    app:
        source-dirs: app/main
        dependencies:
          - base >= 4.12
          - shapes
          - optparse-applicative
          - pinafore-app
        main: Test.hs
        other-modules:
          - Options
        ghc-options: -threaded

benchmarks:
    benchmark:
        source-dirs: benchmark
        dependencies:
          - base >= 4.12
          - shapes
          - changes-core
          - pinafore-language
          - pinafore-gtk
          - criterion
        main: Main.hs
        ghc-options: -threaded
