name: pinafore-app
version: "0.3"
_common: !include "../common.yaml"
<<: *author

<<: *language

extra-doc-files: examples/*

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - shapes
          - time
          - filepath
          - directory
          - optparse-applicative
          - xdg-basedir
          - changes-core
          - changes-gtk
          - pinafore-language
          - pinafore-gtk
          - githash
        main: Main.hs
        other-modules:
          - Options
          - Version
          - Run
          - Documentation
        ghc-options: -threaded -rtsopts

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - pinafore-language
          - pinafore-gtk
        main: Main.hs
        other-modules:
          - Test.Scripts
        ghc-options: -threaded -rtsopts
    app:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - shapes
          - optparse-applicative
        main: Test.hs
        other-modules:
          - Options
        ghc-options: -threaded
