_common: !include "../../common.yaml"
name: pinafore-base
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - thread-trace
      - shapes
      - deepseq
      - time
      - memory
      - blake3
      - changes-core
      - changes-world
    exposed-modules:
      - Pinafore.Base
    other-modules:
      - Pinafore.Base.Know
      - Pinafore.Base.Showable
      - Pinafore.Base.SafeRational
      - Pinafore.Base.Number
      - Pinafore.Base.Literal.Type
      - Pinafore.Base.Literal.Literal
      - Pinafore.Base.Literal.Data
      - Pinafore.Base.Model.FunctionAttribute
      - Pinafore.Base.Model.LensAttribute
      - Pinafore.Base.Model.LensProperty
      - Pinafore.Base.Model.ModelBased
      - Pinafore.Base.Model.ModelProperty
      - Pinafore.Base.Model.ModelOrder
      - Pinafore.Base.Model.Model
      - Pinafore.Base.Anchor
      - Pinafore.Base.Entity
      - Pinafore.Base.KnowShim
      - Pinafore.Base.Storable.EntityStorer
      - Pinafore.Base.Edit
      - Pinafore.Base.Storable.StoreAdapter
      - Pinafore.Base.Model.PredicateProperty
      - Pinafore.Base.Action
      - Pinafore.Base.Model.ImmutableWholeModel
      - Pinafore.Base.File

tests:
    test:
        source-dirs: test
        dependencies:
          - shapes
          - changes-core
          - pinafore-base
        main: Main.hs
        other-modules:
          - Test.Numeric
          - Test.Anchor
          - Test.ReadShow
        ghc-options: -threaded
