_common: !include "../../common.yaml"
name: pinafore-app
version: *pinafore_version
<<: *author

<<: *language

flags:
    gitversion:
        manual: true
        default: true

extra-doc-files: examples/*

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - shapes
      - time
      - filepath
      - xdg-basedir
      - pinafore-language
      - pinafore-lib-media
      - pinafore-lib-gnome
      - pinafore-lib-script
    cpp-options:
      - -DPINAFOREVERSION="0.6"
    when:
      - condition: flag(gitversion)
        dependencies:
          - githash
        cpp-options:
          - -DFLAG_GITVERSION
    exposed-modules:
      - Pinafore.Version
      - Pinafore.Options
      - Pinafore.Libs

executables:
    pinafore:
        source-dirs: app/main
        dependencies:
          - thread-trace
          - shapes
          - optparse-applicative
          - changes-core
          - pinafore-language
          - pinafore-app
        main: Main.hs
        other-modules:
          - Options
          - Run
        ghc-options: -threaded
    pinadata:
        source-dirs: app/data
        dependencies:
          - shapes
          - optparse-applicative
          - aeson
          - pinafore-language
          - pinafore-app
        main: Main.hs
        other-modules:
          - Options
        ghc-options: -threaded

tests:
    test:
        source-dirs: test
        dependencies:
          - filepath
          - directory
          - shapes
          - pinafore-language
          - pinafore-lib-script
          - pinafore-app
        main: Main.hs
        other-modules:
          - Test.Interactive
          - Test.Scripts
          - Test.Library
        ghc-options: -threaded
    app:
        source-dirs: app/main
        dependencies:
          - shapes
          - optparse-applicative
          - pinafore-app
        main: Test.hs
        other-modules:
          - Options
        ghc-options: -threaded

benchmarks:
    benchmark:
        source-dirs: benchmark
        dependencies:
          - base >= 4.16
          - shapes
          - changes-core
          - pinafore-language
          - pinafore-lib-script
          - pinafore-app
          - criterion
        main: Main.hs
        ghc-options: -threaded
