_common: !include "../../common.yaml"
name: changes-gtk
version: *changes_version
<<: *author

<<: *language

flags:
    build-examples:
        description: Build examples
        default: False
        manual: False

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - time
      - vector
      - haskell-gi-base
      - gi-glib
      - gi-gio
      - gi-gobject
      - gi-gdk
      - gi-gdkpixbuf
      - gi-cairo-connector
      - gi-pango
      - gi-gtk
      - gi-gtk-hs
      - shapes
      - cairo-functional
      - changes-core
      - changes-media
    exposed-modules:
      - Changes.UI.GTK
      - Changes.UI.GTK.Test
    other-modules:
      - Changes.GI.Error
      - Changes.GI.Type
      - Changes.GI.ViewLock
      - Changes.GI.LockState
      - Changes.GI.GView
      - Changes.GI.LifeCycle
      - Changes.GI.Signal
      - Changes.GI.Widget
      - Changes.GI.File
      - Changes.GI
      - Changes.UI.GTK.Element.TextStyle
      - Changes.UI.GTK.Element.DynamicStore
      - Changes.UI.GTK.Element.Blank
      - Changes.UI.GTK.Element.Cairo
      - Changes.UI.GTK.Element.CSS
      - Changes.UI.GTK.Element.Button
      - Changes.UI.GTK.Element.Image
      - Changes.UI.GTK.Element.Icon
      - Changes.UI.GTK.Element.Label
      - Changes.UI.GTK.Element.Maybe
      - Changes.UI.GTK.Element.ListBox
      - Changes.UI.GTK.Element.Switch
      - Changes.UI.GTK.Element.CheckButton
      - Changes.UI.GTK.Element.Option
      - Changes.UI.GTK.Element.TextEntry
      - Changes.UI.GTK.Element.Text
      - Changes.UI.GTK.Element.Layout
      - Changes.UI.GTK.Element.Notebook
      - Changes.UI.GTK.Element.Table
      - Changes.UI.GTK.Element.Drag
      - Changes.UI.GTK.Element.MenuBar
      - Changes.UI.GTK.Element.Scrolled
      - Changes.UI.GTK.Element.Calendar
      - Changes.UI.GTK.ChooseFile
      - Changes.UI.GTK.Window
      - Changes.UI.GTK.Main

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - changes-core
          - changes-gtk
          - gi-cairo-render
        main: Main.hs
        ghc-options: -threaded

executables:
    changes-text:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/text
        dependencies:
          - base >= 4.12
          - filepath
          - bytestring
          - shapes
          - changes-core
          - changes-gtk
          - changes-world
          - optparse-applicative
        main: Main.hs
        ghc-options: -threaded
    changes-soup:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/soup
        dependencies:
          - base >= 4.12
          - filepath
          - bytestring
          - uuid
          - aeson
          - shapes
          - changes-core
          - changes-gtk
          - changes-world
          - optparse-applicative
        main: Main.hs
        other-modules:
          - Soup
          - Soup.Note
          - Soup.Edit
          - Soup.UI
        ghc-options: -threaded
    changes-showImages:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/showImages
        dependencies:
          - base >= 4.12
          - filepath
          - directory
          - shapes
          - changes-core
          - changes-media
          - changes-world
          - changes-gtk
        main: Main.hs
        ghc-options: -threaded
    changes-cairo:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/cairo
        dependencies:
          - base >= 4.12
          - shapes
          - time
          - cairo-functional
          - changes-core
          - changes-world
          - changes-gtk
          - gi-cairo-render
          - gi-gtk
        main: Main.hs
        ghc-options: -threaded
