_common: !include "../../common.yaml"
name: changes-gtk
version: *changes_version
<<: *author

<<: *language

flags:
    build-examples:
        description: Build examples
        default: False
        manual: False

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - bytestring
      - text
      - time
      - transformers
      - vector
      - mono-traversable
      - countable
      - witness
      - open-witness
      - haskell-gi-base
      - gi-glib
      - gi-gobject
      - gi-gio
      - gi-gdk
      - gi-gdkpixbuf
      - gi-cairo
      - gi-cairo-render
      - gi-cairo-connector
      - gi-pango
      - gi-gtk
      - gi-gtk-hs
      - shapes
      - changes-core
      - changes-media
    exposed-modules:
      - Graphics.Cairo.Functional
      - Changes.UI.GTK
      - Changes.UI.GTK.Test
    other-modules:
      - Changes.GI.Error
      - Changes.GI.Type
      - Changes.GI.LockState
      - Changes.GI.GView
      - Changes.GI.LifeCycle
      - Changes.GI.Signal
      - Changes.GI.Widget
      - Changes.GI
      - Changes.UI.GTK.TextStyle
      - Changes.UI.GTK.DynamicStore
      - Changes.UI.GTK.Blank
      - Changes.UI.GTK.Cairo
      - Changes.UI.GTK.CSS
      - Changes.UI.GTK.Button
      - Changes.UI.GTK.Image
      - Changes.UI.GTK.Icon
      - Changes.UI.GTK.Label
      - Changes.UI.GTK.Maybe
      - Changes.UI.GTK.ListBox
      - Changes.UI.GTK.Switch
      - Changes.UI.GTK.CheckButton
      - Changes.UI.GTK.Option
      - Changes.UI.GTK.TextEntry
      - Changes.UI.GTK.Text
      - Changes.UI.GTK.Layout
      - Changes.UI.GTK.Notebook
      - Changes.UI.GTK.Table
      - Changes.UI.GTK.Drag
      - Changes.UI.GTK.MenuBar
      - Changes.UI.GTK.Scrolled
      - Changes.UI.GTK.Calendar
      - Changes.UI.GTK.ChooseFile
      - Changes.UI.GTK.Window
      - Changes.UI.GTK.Main

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - changes-core
          - changes-gtk
          - gi-cairo-render
        main: Main.hs
        ghc-options: -threaded

executables:
    changes-text:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/text
        dependencies:
          - base >= 4.12
          - filepath
          - bytestring
          - shapes
          - changes-core
          - changes-gtk
          - changes-world
          - optparse-applicative
        main: Main.hs
        ghc-options: -threaded
    changes-soup:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/soup
        dependencies:
          - base >= 4.12
          - filepath
          - bytestring
          - uuid
          - aeson
          - shapes
          - changes-core
          - changes-gtk
          - changes-world
          - optparse-applicative
        main: Main.hs
        other-modules:
          - Soup
          - Soup.Note
          - Soup.Edit
          - Soup.UI
        ghc-options: -threaded
    changes-showImages:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/showImages
        dependencies:
          - base >= 4.12
          - filepath
          - directory
          - shapes
          - changes-core
          - changes-media
          - changes-world
          - changes-gtk
        main: Main.hs
        ghc-options: -threaded
    changes-cairo:
        when:
          - condition: "!flag(build-examples)"
            buildable: False
        source-dirs: examples/cairo
        dependencies:
          - base >= 4.12
          - shapes
          - time
          - changes-core
          - changes-world
          - changes-gtk
          - gi-cairo-render
          - gi-gtk
        main: Main.hs
        ghc-options: -threaded
