_common: !include "../../common.yaml"
name: pinafore-docgen
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - shapes
      - pinafore-language
    exposed-modules:
      - Pinafore.DocGen

executables:
    pinadoc:
        source-dirs: app
        dependencies:
          - shapes
          - optparse-applicative
          - pinafore-language
          - pinafore-app
          - pinafore-docgen
        main: Main.hs
        other-modules:
          - Options
        ghc-options: -threaded

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - shapes
          - filepath
          - pinafore-language
          - pinafore-app
          - pinafore-docgen
        main: Main.hs
        ghc-options: -threaded
