name: shapes
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      - base >= 4.12
      - time
      - stm
      - constraints
      - mono-traversable
      - contravariant
      - comonad
      - lattices
      - transformers
      - transformers-extra
      - hashable
      - containers
      - unordered-containers
      - bytestring
      - cereal
      - text
      - cereal-text
      - random
      - countable
      - witness
      - open-witness
    exposed-modules:
      - Control.Category.Groupoid
      - Data.Filterable
      - Data.MonoApplicative
      - Data.CatFunctor
      - Data.Coercion
      - Data.Result
      - Data.SameItem
      - Data.MonadOne
      - Data.HasNewValue
      - Data.IsoVariant
      - Data.Injection
      - Data.Bijection
      - Data.Lens
      - Data.Store
      - Data.ConstFunction
      - Data.CoerceFunction
      - Data.Codec
      - Data.Compose
      - Data.KeyContainer
      - Data.FiniteSet
      - Data.KindMorphism
      - Control.Category.Dual
      - Control.Monad.Compose
      - Control.Monad.Coroutine
      - Control.Monad.Trans.LifeCycle
      - Control.Monad.LifeCycleIO
      - Control.Clock
      - Control.AsyncRunner
      - Shapes
      - Shapes.Numeric
    other-modules:
      - Shapes.Import
      - Shapes.Instances

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - time
          - shapes
          - tasty
          - tasty-hunit
        main: Main.hs
        ghc-options: -threaded
