name: shapes
version: "0.2"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      # core
      - base >= 4.12
      - time
      - containers
      - stm
      # general
      - constraints
      - mono-traversable
      - contravariant
      - comonad
      - lattices
      - transformers
      - hashable
      - unordered-containers
      - bytestring
      - cereal
      - text
      - cereal-text
      - random
      # test
      - directory
      - filepath
      - tasty
      - tasty-expected-failure
      - tasty-hunit
      - tasty-golden
      - QuickCheck
      - tasty-quickcheck
      # mine
      - countable
      - witness
      - open-witness
      - transformers-extra
      - thread-trace
    exposed-modules:
      - Control.Category.Groupoid
      - Data.Filterable
      - Data.MonoApplicative
      - Data.CatFunctor
      - Data.Coercion
      - Data.Result
      - Data.SameItem
      - Data.MonadOne
      - Data.HasNewValue
      - Data.IsoVariant
      - Data.Injection
      - Data.Isomorphism
      - Data.Lens
      - Data.Store
      - Data.ConstFunction
      - Data.CoerceFunction
      - Data.Codec
      - Data.Compose
      - Data.KeyedOrder
      - Data.KeyContainer
      - Data.FiniteSet
      - Data.KindMorphism
      - Data.FixBox
      - Control.Category.Dual
      - Control.Category.Lifted
      - Control.Applicative.Compose
      - Control.Monad.Compose
      - Control.Monad.Exception
      - Control.Monad.Coroutine
      - Control.Monad.LifeCycle
      - Control.Clock
      - Control.Task
      - Control.AsyncRunner
      - Unsafe.Type
      - Shapes
      - Shapes.Numeric
      - Shapes.Unsafe
      - Shapes.Test
    other-modules:
      - Shapes.Import
      - Shapes.Instances

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - time
          - shapes
        main: Main.hs
        ghc-options: -threaded
