name: shapes
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      - base >= 4.9 && < 5
      - stm
      - constraints
      - mono-traversable
      - comonad
      - lattices
      - transformers
      - transformers-extra
      - hashable
      - containers
      - unordered-containers
      - bytestring
      - cereal
      - text
      - cereal-text
      - random
      - countable
      - witness
      - open-witness
    exposed-modules:
      - Data.Filterable
      - Data.CatFunctor
      - Data.Result
      - Data.OneItem
      - Data.MonadOne
      - Data.HasNewValue
      - Data.Injection
      - Data.Bijection
      - Data.Lens
      - Data.Store
      - Data.ConstFunction
      - Data.Codec
      - Data.Compose
      - Data.KeyContainer
      - Data.FiniteSet
      - Control.Monad.Compose
      - Control.LifeCycle
      - Shapes
    other-modules:
      - Shapes.Import

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.9 && < 5
          - shapes
          - tasty
          - tasty-hunit
        main: Main.hs
        other-modules:
