_common: !include "../../common.yaml"
name: pinafore-media
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - polar-shim
      - typed-expression
      - Color
      - gi-cairo-render
      - cairo-functional
      - changes-core
      - changes-world
      - changes-media
      - pinafore-base
      - pinafore-language
    exposed-modules:
      - Pinafore.Language.Library.Media
    other-modules:
      - Pinafore.Language.Library.Media.Colour
      - Pinafore.Language.Library.Media.Image.Image
      - Pinafore.Language.Library.Media.Image.PNG
      - Pinafore.Language.Library.Media.Image.JPEG
      - Pinafore.Language.Library.Media.Image
      - Pinafore.Language.Library.Media.Cairo
