name: typed-expression
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
    exposed-modules:
      - Data.Shim
      - Language.Expression.Common
      - Language.Expression.Unitype
      - Language.Expression.TypeVariable
      - Language.Expression.Dolan
    other-modules:
      - Data.Shim.PolyMap
      - Data.Shim.Polarity
      - Data.Shim.PolarMap
      - Data.Shim.Variance
      - Data.Shim.PolarVariance
      - Data.Shim.ShimWit
      - Data.Shim.Range
      - Data.Shim.CatRange
      - Data.Shim.JoinMeet
      - Data.Shim.PolarJoinMeet
      - Data.Shim.PolyShim
      - Data.Shim.JMShim
      - Data.Shim.PolyIso
      - Data.Shim.JMShimWit
      - Language.Expression.Common.Error
      - Language.Expression.Common.WitnessMappable
      - Language.Expression.Common.Witness
      - Language.Expression.Common.Expression
      - Language.Expression.Common.Pattern
      - Language.Expression.Common.NameWit
      - Language.Expression.Common.Named
      - Language.Expression.Common.Sealed
      - Language.Expression.Common.Renamer
      - Language.Expression.Common.Unifier
      - Language.Expression.Common.Subsumer
      - Language.Expression.Common.Abstract
      - Language.Expression.Common.Bindings
      - Language.Expression.Common.TypeSystem
      - Language.Expression.Common.Arguments
      - Language.Expression.Dolan.PShimWit
      - Language.Expression.Dolan.Covariance
      - Language.Expression.Dolan.Variance
      - Language.Expression.Dolan.Arguments
      - Language.Expression.Dolan.MPolarity
      - Language.Expression.Dolan.RangeF
      - Language.Expression.Dolan.Type
      - Language.Expression.Dolan.Subtype
      - Language.Expression.Dolan.Bisubstitute
      - Language.Expression.Dolan.TypeSystem
      - Language.Expression.Dolan.Rename
      - Language.Expression.Dolan.Simplify.VarUses
      - Language.Expression.Dolan.Simplify.OneSidedTypeVars
      - Language.Expression.Dolan.Simplify.DuplicateGroundTypes
      - Language.Expression.Dolan.Simplify.SharedTypeVars
      - Language.Expression.Dolan.Simplify.DuplicateTypeVars
      - Language.Expression.Dolan.Simplify
      - Language.Expression.Dolan.Unify
      - Language.Expression.Dolan.Inverted
      - Language.Expression.Dolan.Subsume
      - Language.Expression.Dolan.Nonpolar
