name: pinafore
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.9 && < 5
      - time
      - containers
      - filepath
      - directory
      - cereal
      - uuid
      - aeson
      - sqlite-simple
      - shapes
      - parsec
      - memory
      - cryptonite
      - truth-core
    exposed-modules:
      - Language.Expression.Witness
      - Language.Expression.Expression
      - Language.Expression.NameWit
      - Language.Expression.Named
      - Language.Expression.Sealed
      - Language.Expression.Renamer
      - Language.Expression.Unifier
      - Language.Expression.Abstract
      - Language.Expression.Bindings
      - Language.Expression.Typed
      - Language.Expression.Unitype
      - Language.Expression.Dolan
      - Pinafore.Base
      - Pinafore.Storage
      - Pinafore.Language
      - Pinafore.Main
      - Pinafore.Pinafore
      - Pinafore
      - Pinafore.Test
    other-modules:
      - Language.Expression.UVar
      - Language.Expression.Dolan.Range
      - Language.Expression.Dolan.Polarity
      - Language.Expression.Dolan.Variance
      - Language.Expression.Dolan.Arguments
      - Language.Expression.Dolan.TypeF
      - Language.Expression.Dolan.MPolarity
      - Language.Expression.Dolan.RangeF
      - Pinafore.Base.Know
      - Pinafore.Base.Number
      - Pinafore.Base.Literal
      - Pinafore.Base.Morphism
      - Pinafore.Base.Point
      - Pinafore.Base.Edit
      - Pinafore.Base.Entity
      - Pinafore.Base.PredicateMorphism
      - Pinafore.Base.Action
      - Pinafore.Base.ImmutableReference
      - Pinafore.Language.Name
      - Pinafore.Language.Literal
      - Pinafore.Language.NamedEntity
      - Pinafore.Language.SimpleEntityType
      - Pinafore.Language.Reference
      - Pinafore.Language.Set
      - Pinafore.Language.Morphism
      - Pinafore.Language.Token
      - Pinafore.Language.RefNotation
      - Pinafore.Language.Read
      - Pinafore.Language.If
      - Pinafore.Language.Show
      - Pinafore.Language.Order
      - Pinafore.Language.GroundType
      - Pinafore.Language.TypeContext
      - Pinafore.Language.Convert.Base
      - Pinafore.Language.Type
      - Pinafore.Language.Expression
      - Pinafore.Language.Convert
      - Pinafore.Language.Doc
      - Pinafore.Language.Predefined
      - Pinafore.Storage.Table
      - Pinafore.Storage.Database
      - Pinafore.Storage.Database.SQLite
      - Pinafore.Storage.File

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.9 && < 5
          - bytestring
          - containers
          - countable
          - open-witness
          - template-haskell
          - transformers
          - witness
          - comonad
          - mono-traversable
          - shapes
          - truth-core
          - pinafore
          - QuickCheck
          - tasty
          - tasty-hunit
          - tasty-quickcheck
          - tasty-golden
        main: Main.hs
        other-modules:
          - Test.Language
          - Test.Entity
          - Test.Type
          - Test.ReadType

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.9 && < 5
          - filepath
          - bytestring
          - shapes
          - truth-core
          - truth-gtk
          - pinafore
          - directory
          - optparse-applicative
          - xdg-basedir
        main: Main.hs
        ghc-options: -threaded
