name: pinafore
version: "0.2"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - filepath
      - directory
      - parsec
      - containers
      - typed-expression
      - changes-core
      - changes-world
      - changes-gtk
      - pinafore-base
    exposed-modules:
      - Pinafore.Language
      - Pinafore.Language.Documentation
      - Pinafore.Main
      - Pinafore
      - Pinafore.Test
    other-modules:
      - Pinafore.Context
      - Pinafore.Language.Value.Instances
      - Pinafore.Language.Value.WholeRef
      - Pinafore.Language.Value.SetRef
      - Pinafore.Language.Value.FiniteSetRef
      - Pinafore.Language.Value.ListRef
      - Pinafore.Language.Value.TextRef
      - Pinafore.Language.Value.Morphism
      - Pinafore.Language.Value.RefOrder
      - Pinafore.Language.Value.UI
      - Pinafore.Language.Value
      - Pinafore.Language.Name
      - Pinafore.Language.Shim
      - Pinafore.Language.Type.Literal
      - Pinafore.Language.If
      - Pinafore.Language.Type.Show
      - Pinafore.Language.Type.Ground
      - Pinafore.Language.Type.Data
      - Pinafore.Language.Type.Identified
      - Pinafore.Language.Error
      - Pinafore.Language.Subtype
      - Pinafore.Language.SpecialForm
      - Pinafore.Language.Interpret.Interpreter
      - Pinafore.Language.Var
      - Pinafore.Language.Convert.Base
      - Pinafore.Language.Type.Type
      - Pinafore.Language.Type.Subtype
      - Pinafore.Language.Type
      - Pinafore.Language.Type.DynamicEntity
      - Pinafore.Language.Type.Entity
      - Pinafore.Language.Type.OpenEntity
      - Pinafore.Language.Type.EntityAdapter
      - Pinafore.Language.Type.DynamicSupertype
      - Pinafore.Language.Syntax
      - Pinafore.Language.Read.Token
      - Pinafore.Language.Interpret.RefNotation
      - Pinafore.Language.Read.Parser
      - Pinafore.Language.Read.Type
      - Pinafore.Language.Read.TypeDecls
      - Pinafore.Language.Read.Infix
      - Pinafore.Language.Read.Constructor
      - Pinafore.Language.Read.Pattern
      - Pinafore.Language.Read.Expression
      - Pinafore.Language.Read.Interactive
      - Pinafore.Language.Read
      - Pinafore.Language.Interpret.Type
      - Pinafore.Language.Interpret.TypeDecl
      - Pinafore.Language.Interpret
      - Pinafore.Language.Expression
      - Pinafore.Language.Convert
      - Pinafore.Language.DocTree
      - Pinafore.Language.Predefined.Defs
      - Pinafore.Language.Predefined.SpecialForms
      - Pinafore.Language.Predefined.Base
      - Pinafore.Language.Predefined.UI
      - Pinafore.Language.Predefined.File
      - Pinafore.Language.Predefined

extra-doc-files: examples/*

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - filepath
          - parsec
          - gi-gtk
          - gi-gobject
          - haskell-gi-base
          - typed-expression
          - changes-core
          - changes-gtk
          - pinafore
        main: Main.hs
        other-modules:
          - Test.Context
          - Test.Language
          - Test.Entity
          - Test.Type
          - Test.ReadType
          - Test.Scripts
          - Test.Output
          - Test.Module
          - Test.Interactive
          - Test.UI
        ghc-options: -threaded
    app:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - shapes
          - optparse-applicative
        main: Test.hs
        other-modules:
          - Options
        ghc-options: -threaded

benchmarks:
    benchmark:
        source-dirs: benchmark
        dependencies:
          - base >= 4.12
          - shapes
          - changes-core
          - pinafore
          - criterion
        main: Main.hs
        ghc-options: -threaded

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - shapes
          - time
          - filepath
          - directory
          - optparse-applicative
          - xdg-basedir
          - changes-core
          - changes-gtk
          - pinafore
          - githash
        main: Main.hs
        other-modules:
          - Options
          - Version
          - Run
          - Documentation
        ghc-options: -threaded
