name: pinafore
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - filepath
      - parsec
      - containers
      - typed-expression
      - truth-core
      - truth-world
      - pinafore-base
    exposed-modules:
      - Pinafore.Language
      - Pinafore.Language.Documentation
      - Pinafore.Main
      - Pinafore
      - Pinafore.Test
    other-modules:
      - Pinafore.Language.Value.Instances
      - Pinafore.Language.Value.OpenEntity
      - Pinafore.Language.Value.Ref
      - Pinafore.Language.Value.SetRef
      - Pinafore.Language.Value.FiniteSetRef
      - Pinafore.Language.Value.ListRef
      - Pinafore.Language.Value.TextRef
      - Pinafore.Language.Value.Morphism
      - Pinafore.Language.Value.Order
      - Pinafore.Language.Value.UI
      - Pinafore.Language.Value
      - Pinafore.Language.Name
      - Pinafore.Language.Type.Literal
      - Pinafore.Language.If
      - Pinafore.Language.TypeSystem.Show
      - Pinafore.Language.Type.Ground
      - Pinafore.Language.TypeSystem.Nonpolar
      - Pinafore.Language.Type.Data
      - Pinafore.Language.Type.TypeID
      - Pinafore.Language.Error
      - Pinafore.Language.Subtype
      - Pinafore.Language.Scope
      - Pinafore.Language.Convert.Base
      - Pinafore.Language.TypeSystem.Type
      - Pinafore.Language.TypeSystem.Subtype
      - Pinafore.Language.TypeSystem.Rename
      - Pinafore.Language.TypeSystem.Bisubstitute
      - Pinafore.Language.TypeSystem.Simplify.VarUses
      - Pinafore.Language.TypeSystem.Simplify.OneSidedTypeVars
      - Pinafore.Language.TypeSystem.Simplify.DuplicateGroundTypes
      - Pinafore.Language.TypeSystem.Simplify.SharedTypeVars
      - Pinafore.Language.TypeSystem.Simplify.DuplicateTypeVars
      - Pinafore.Language.TypeSystem.Simplify
      - Pinafore.Language.TypeSystem.Unify
      - Pinafore.Language.TypeSystem.Inverted
      - Pinafore.Language.TypeSystem.Subsume
      - Pinafore.Language.TypeSystem
      - Pinafore.Language.Type.Entity
      - Pinafore.Language.Type.EntityAdapter
      - Pinafore.Language.Syntax
      - Pinafore.Language.Read.Token
      - Pinafore.Language.Read.RefNotation
      - Pinafore.Language.Read.Parser
      - Pinafore.Language.Read.Type
      - Pinafore.Language.Read.TypeDecls
      - Pinafore.Language.Read.Infix
      - Pinafore.Language.Read.Constructor
      - Pinafore.Language.Read.Pattern
      - Pinafore.Language.Read.Expression
      - Pinafore.Language.Read.Interactive
      - Pinafore.Language.Read
      - Pinafore.Language.Interpret.Type
      - Pinafore.Language.Interpret
      - Pinafore.Language.Expression
      - Pinafore.Language.Convert
      - Pinafore.Language.DocTree
      - Pinafore.Language.Predefined.Defs
      - Pinafore.Language.Predefined.Base
      - Pinafore.Language.Predefined.UI
      - Pinafore.Language.Predefined.File
      - Pinafore.Language.Predefined

extra-doc-files: examples/*

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - filepath
          - gi-gtk
          - gi-gobject
          - haskell-gi-base
          - typed-expression
          - truth-core
          - truth-gtk
          - pinafore
          - tasty
          - tasty-expected-failure
          - tasty-hunit
          - tasty-golden
        main: Main.hs
        other-modules:
          - Test.Context
          - Test.Language
          - Test.Entity
          - Test.Type
          - Test.ReadType
          - Test.Scripts
          - Test.Interactive
          - Test.UI
        ghc-options: -threaded

benchmarks:
    benchmark:
        source-dirs: benchmark
        dependencies:
          - base >= 4.12
          - shapes
          - truth-core
          - pinafore
          - criterion
        main: Main.hs
        ghc-options: -threaded

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - shapes
          - time
          - directory
          - optparse-applicative
          - xdg-basedir
          - truth-core
          - truth-gtk
          - pinafore
          - githash
        main: Main.hs
        other-modules:
          - Options
          - Version
          - Run
          - Documentation
        ghc-options: -threaded
