name: pinafore
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.9 && < 5
      - time
      - containers
      - filepath
      - directory
      - cereal
      - uuid
      - aeson
      - sqlite-simple
      - shapes
      - parsec
      - truth-core
    exposed-modules:
      - Pinafore
      - Pinafore.Main
      - Pinafore.Query.Value
      - Pinafore.Query.Convert
      - Pinafore.Query.Expression
      - Pinafore.Query
    other-modules:
      - Pinafore.Number
      - Pinafore.Literal
      - Pinafore.Morphism
      - Pinafore.Entity
      - Pinafore.Table
      - Pinafore.File
      - Pinafore.Pinafore
      - Pinafore.Query.Token
      - Pinafore.Query.Read
      - Pinafore.Query.Types
      - Pinafore.Query.Lifted
      - Pinafore.Query.Order
      - Pinafore.Query.Predefined
      - Pinafore.Database
      - Pinafore.Database.SQLite

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.9 && < 5
          - bytestring
          - containers
          - countable
          - open-witness
          - template-haskell
          - transformers
          - witness
          - comonad
          - mono-traversable
          - shapes
          - truth-core
          - pinafore
          - QuickCheck
          - tasty
          - tasty-hunit
          - tasty-quickcheck
          - tasty-golden
        main: Main.hs
        other-modules:

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.9 && < 5
          - filepath
          - bytestring
          - shapes
          - truth-core
          - truth-gtk
          - pinafore
          - directory
          - optparse-applicative
          - xdg-basedir
        main: Main.hs
        ghc-options: -threaded
