name: pinafore
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - time
      - deepseq
      - containers
      - filepath
      - directory
      - cereal
      - uuid
      - aeson
      - sqlite-simple
      - shapes
      - parsec
      - memory
      - cryptonite
      - truth-core
    exposed-modules:
      - Data.Shim
      - Language.Expression.WitnessMappable
      - Language.Expression.Witness
      - Language.Expression.Expression
      - Language.Expression.Pattern
      - Language.Expression.NameWit
      - Language.Expression.Named
      - Language.Expression.Sealed
      - Language.Expression.Renamer
      - Language.Expression.Unifier
      - Language.Expression.Subsumer
      - Language.Expression.Abstract
      - Language.Expression.Bindings
      - Language.Expression.TypeSystem
      - Language.Expression.Unitype
      - Language.Expression.Dolan
      - Pinafore.Base
      - Pinafore.Storage
      - Pinafore.Language
      - Pinafore.Language.Documentation
      - Pinafore.Main
      - Pinafore.Pinafore
      - Pinafore
      - Pinafore.Test
    other-modules:
      - Data.Shim.Polarity
      - Data.Shim.ShimWit
      - Data.Shim.Range
      - Data.Shim.JoinMeet
      - Data.Shim.PolyShim
      - Data.Shim.MapRange
      - Data.Shim.JMShim
      - Data.Shim.JMShimWit
      - Language.Expression.Error
      - Language.Expression.UVar
      - Language.Expression.Dolan.PShimWit
      - Language.Expression.Dolan.Variance
      - Language.Expression.Dolan.Arguments
      - Language.Expression.Dolan.MPolarity
      - Language.Expression.Dolan.RangeF
      - Pinafore.Base.Know
      - Pinafore.Base.Number
      - Pinafore.Base.Literal
      - Pinafore.Base.Morphism
      - Pinafore.Base.Entity
      - Pinafore.Base.Lens
      - Pinafore.Base.Edit
      - Pinafore.Base.EntityAdapter
      - Pinafore.Base.PredicateMorphism
      - Pinafore.Base.Action
      - Pinafore.Base.Context
      - Pinafore.Base.ImmutableReference
      - Pinafore.Language.Name
      - Pinafore.Language.Literal
      - Pinafore.Language.OpenEntity
      - Pinafore.Language.Reference
      - Pinafore.Language.SetRef
      - Pinafore.Language.Morphism
      - Pinafore.Language.If
      - Pinafore.Language.Show
      - Pinafore.Language.Order
      - Pinafore.Language.UI
      - Pinafore.Language.GroundType
      - Pinafore.Language.TypeID
      - Pinafore.Language.Error
      - Pinafore.Language.Scope
      - Pinafore.Language.Convert.Base
      - Pinafore.Language.Type.Type
      - Pinafore.Language.Type.Subtype
      - Pinafore.Language.Type.Rename
      - Pinafore.Language.Type.Bisubstitute
      - Pinafore.Language.Type.Simplify.VarUses
      - Pinafore.Language.Type.Simplify.OneSidedTypeVars
      - Pinafore.Language.Type.Simplify.DuplicateGroundTypes
      - Pinafore.Language.Type.Simplify.SharedTypeVars
      - Pinafore.Language.Type.Simplify.DuplicateTypeVars
      - Pinafore.Language.Type.Simplify
      - Pinafore.Language.Type.Unify
      - Pinafore.Language.Type.Inverted
      - Pinafore.Language.Type.Subsume
      - Pinafore.Language.Type
      - Pinafore.Language.EntityType
      - Pinafore.Language.Syntax
      - Pinafore.Language.Read.Token
      - Pinafore.Language.Read.RefNotation
      - Pinafore.Language.Read.Parser
      - Pinafore.Language.Read.Type
      - Pinafore.Language.Read.TypeDecls
      - Pinafore.Language.Read.Infix
      - Pinafore.Language.Read.Constructor
      - Pinafore.Language.Read.Pattern
      - Pinafore.Language.Read.Expression
      - Pinafore.Language.Read.Interactive
      - Pinafore.Language.Read
      - Pinafore.Language.Interpret.Type
      - Pinafore.Language.Interpret
      - Pinafore.Language.Expression
      - Pinafore.Language.Convert
      - Pinafore.Language.DocTree
      - Pinafore.Language.Predefined.Defs
      - Pinafore.Language.Predefined.Base
      - Pinafore.Language.Predefined.UI
      - Pinafore.Language.Predefined.File
      - Pinafore.Language.Predefined
      - Pinafore.Storage.Table
      - Pinafore.Storage.Database
      - Pinafore.Storage.Database.SQLite
      - Pinafore.Storage.File

extra-doc-files: examples/*

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - bytestring
          - containers
          - countable
          - open-witness
          - template-haskell
          - transformers
          - witness
          - comonad
          - mono-traversable
          - shapes
          - truth-core
          - gi-gobject
          - haskell-gi-base
          - gi-gdk
          - gi-gtk
          - truth-gtk
          - pinafore
          - filepath
          - QuickCheck
          - tasty
          - tasty-hunit
          - tasty-quickcheck
          - tasty-golden
        main: Main.hs
        other-modules:
          - Test.Context
          - Test.Language
          - Test.Entity
          - Test.Type
          - Test.ReadType
          - Test.Scripts
          - Test.Interactive
          - Test.UI
        ghc-options: -threaded

benchmarks:
    benchmark:
        source-dirs: benchmark
        dependencies:
          - base >= 4.12
          - criterion
          - shapes
          - truth-core
          - pinafore
        main: Main.hs
        ghc-options: -threaded

executables:
    pinafore:
        source-dirs: app
        dependencies:
          - base >= 4.12
          - filepath
          - bytestring
          - shapes
          - truth-core
          - truth-gtk
          - pinafore
          - directory
          - optparse-applicative
          - xdg-basedir
          - time
          - githash
        main: Main.hs
        ghc-options: -threaded
