---
name: pinafore
version: "0.5.0"
license: "SEE LICENSE IN LICENSE"
publisher: "Pinafore"
displayName: "Pinafore"
description: "Pinafore language support"

engines:
  vscode: "^1.29.0"

categories:
- "Programming Languages"

contributes:
  languages:
  - id: pinafore
    aliases:
    - Pinafore
    - pinafore
    extensions:
    - ".pinafore"
    firstLine: "^#!/.*\\bpinafore\\b"
    configuration: "./language-configuration.json"
  grammars:
  - language: pinafore
    scopeName: source.pinafore
    path: "./syntaxes/pinafore.tmLanguage.json"

repository:
  type: git
  url: "https://github.com/AshleyYakeley/Truth.git"

homepage: "https://pinafore.info/"
