name: transformers-extra
version: "0.1"
_common: !include "../common.yaml"
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      - base >= 4.12
      - constraints
      - transformers
    exposed-modules:
      - Control.Monad.Trans.Constraint
      - Control.Monad.Trans.Tunnel
      - Control.Monad.Trans.Transform
      - Control.Monad.Trans.Unlift
      - Control.Monad.Trans.AskUnlift
      - Control.Monad.Trans.Compose
      - Control.Monad.Trans.Free
      - Control.Monad.Trans.StackIO
      - Control.Monad.Trans.ContExtra
      - Control.Monad.Trans.ReaderState
