_common: !include "../../common.yaml"
name: pinafore-webapi
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - insert-ordered-containers
      - network-uri
      - aeson
      - openapi3
      - shapes
      - polar-shim
      - pinafore-language
    exposed-modules:
      - Pinafore.WebAPI
    other-modules:
      - Pinafore.WebAPI.JSONType
      - Pinafore.WebAPI.Fetch
      - Pinafore.WebAPI.OpenAPI.Schema
      - Pinafore.WebAPI.OpenAPI

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - shapes
          - pinafore-language
          - pinafore-webapi
        main: Main.hs
        ghc-options: -threaded
