_common: !include "../../common.yaml"
name: pinafore-webapi
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.16
      - shapes
      - pinafore-language
    exposed-modules:
      - Pinafore.WebAPI
    other-modules:
      - Pinafore.WebAPI.Fetch
      - Pinafore.WebAPI.OpenAPI
