_common: !include "../../common.yaml"
name: typed-expression
version: *pinafore_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - base >= 4.12
      - shapes
      - time
      - thread-trace
      - polar-shim
    exposed-modules:
      - Language.Expression.Common
      - Language.Expression.Unitype
      - Language.Expression.Dolan
      - Language.Expression.Dolan.Test
    other-modules:
      - Control.Applicative.Wrapped
      - Language.Expression.Common.Error
      - Language.Expression.Common.WitnessMappable
      - Language.Expression.Common.Witness
      - Language.Expression.Common.Expression
      - Language.Expression.Common.Pattern.Pattern
      - Language.Expression.Common.Pattern.Named
      - Language.Expression.Common.Pattern.Sealed
      - Language.Expression.Common.Pattern.Constructor
      - Language.Expression.Common.Pattern.Expression
      - Language.Expression.Common.Pattern
      - Language.Expression.Common.NameWit
      - Language.Expression.Common.Named
      - Language.Expression.Common.Sealed
      - Language.Expression.Common.TypeSystem
      - Language.Expression.Common.TypeFunction
      - Language.Expression.Common.TypeVariable
      - Language.Expression.Common.Rename.RenameTypeSystem
      - Language.Expression.Common.Rename.Rigidity
      - Language.Expression.Common.Rename.VarNamespaceT
      - Language.Expression.Common.Rename.VarRenamerT
      - Language.Expression.Common.Rename.NamespaceRenamable
      - Language.Expression.Common.Rename
      - Language.Expression.Common.Simplifier
      - Language.Expression.Common.SolverExpression
      - Language.Expression.Common.Unifier
      - Language.Expression.Common.Subsumer
      - Language.Expression.Common.Abstract
      - Language.Expression.Common.Bindings
      - Language.Expression.Common.CompleteTypeSystem
      - Language.Expression.Common.Arguments
      - Language.Expression.Dolan.PShimWit
      - Language.Expression.Dolan.Covariance
      - Language.Expression.Dolan.Variance
      - Language.Expression.Dolan.Argument
      - Language.Expression.Dolan.Arguments
      - Language.Expression.Dolan.MPolarity
      - Language.Expression.Dolan.RangeF
      - Language.Expression.Dolan.Type
      - Language.Expression.Dolan.Occur
      - Language.Expression.Dolan.Subtype
      - Language.Expression.Dolan.Bisubstitute
      - Language.Expression.Dolan.TypeSystem
      - Language.Expression.Dolan.Rename
      - Language.Expression.Dolan.Combine
      - Language.Expression.Dolan.Unroll
      - Language.Expression.Dolan.InvertedCombine
      - Language.Expression.Dolan.Simplify.UnusedRecursion
      - Language.Expression.Dolan.Simplify.VarUses
      - Language.Expression.Dolan.Simplify.VarUsage
      - Language.Expression.Dolan.Simplify.OneSidedTypeVars
      - Language.Expression.Dolan.Simplify.FullyConstrainedTypeVars
      - Language.Expression.Dolan.Simplify.DuplicateGroundTypes
      - Language.Expression.Dolan.Simplify.SharedTypeVars
      - Language.Expression.Dolan.Simplify.DuplicateTypeVars
      - Language.Expression.Dolan.Simplify.RollUpRecursion
      - Language.Expression.Dolan.Simplify
      - Language.Expression.Dolan.Invert
      - Language.Expression.Dolan.Solver
      - Language.Expression.Dolan.Unifier.UnifierM
      - Language.Expression.Dolan.Unifier.Constraint
      - Language.Expression.Dolan.Unifier.Build
      - Language.Expression.Dolan.Unifier
      - Language.Expression.Dolan.Nonpolar
      - Language.Expression.Dolan.Mono

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - shapes
          - polar-shim
          - typed-expression
        main: Main.hs
        other-modules:
          - Shim
        ghc-options: -threaded
