_common: !include "../../common.yaml"
name: shapes
version: *changes_version
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      # core
      - base >= 4.12
      - time
      - containers
      - stm
      # general
      - constraints
      - mono-traversable
      - contravariant
      - comonad
      - invariant
      - lattices
      - transformers
      - hashable
      - unordered-containers
      - bytestring
      - vector
      - cereal
      - text
      - cereal-text
      - random
      # test
      - directory
      - filepath
      - tasty
      - tasty-expected-failure
      - tasty-hunit
      - tasty-golden
      - QuickCheck
      - tasty-quickcheck
      # mine
      - countable
      - witness
      - open-witness
      - type-rig
      - monadology
      - thread-trace
    exposed-modules:
      - Data.Words
      - Control.Category.Groupoid
      - Control.FixIO
      - Data.CatEndo
      - Data.Filterable
      - Data.MonoApplicative
      - Data.CatFunctor
      - Data.Coercion
      - Data.SameItem
      - Data.HasNewValue
      - Data.Streamable
      - Data.Injection
      - Data.Isomorphism
      - Data.Lens
      - Data.Store
      - Data.ConstFunction
      - Data.CoerceFunction
      - Data.PurityFunction
      - Data.Codec
      - Data.KeyedOrder
      - Data.KeyContainer
      - Data.FiniteSet
      - Data.KindMorphism
      - Data.FixBox
      - Data.Serializer
      - Data.Serialize.Instances
      - Data.ReadShow
      - Control.Category.Dual
      - Control.Category.Lifted
      - Control.Clock
      - Control.Task
      - Control.Stream.Filter
      - Control.Stream.Sink
      - Control.Stream.Source
      - Control.Stream
      - Control.CallbackLock
      - Control.AsyncRunner
      - Unsafe.Type
      - Unsafe.IO
      - Shapes
      - Shapes.Numeric
      - Shapes.Unsafe
      - Shapes.Test
      - Shapes.Test.Context
    other-modules:
      - Unsafe.Refl
      - Shapes.Import
      - Shapes.Instances

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.12
          - time
          - shapes
        main: Main.hs
        ghc-options: -threaded
