_common: !include "../../common.yaml"
name: shapes
version: *changes_version
<<: *author

<<: *language

library:
    source-dirs: src
    dependencies:
      # core
      - base >= 4.16
      - time
      - containers
      - stm
      # general
      - constraints
      - mono-traversable
      - comonad
      - invariant
      - lattices
      - hashable
      - unordered-containers
      - bytestring
      - vector
      - text
      - random
      - leb128
      - reflection
      # test
      - directory
      - filepath
      - tasty
      - tasty-expected-failure
      - tasty-hunit
      - tasty-golden
      - QuickCheck
      - tasty-quickcheck
      # mine
      - countable
      - witness
      - open-witness
      - type-rig
      - monadology
      - primitive-serial
      - thread-trace
    exposed-modules:
      - Data.Words
      - Data.Char8
      - Data.Sequential
      - Data.Hexadecimal
      - Control.Category.Groupoid
      - Control.Applicative.Wrapped
      - Control.FixIO
      - Data.CatEndo
      - Data.EndoM
      - Data.Filterable
      - Data.MonoApplicative
      - Data.CatFunctor
      - Data.Coerce.Coercion
      - Data.Coerce.Role
      - Data.Coerce.MaybeRepresentational
      - Data.Wrappable
      - Data.Givable
      - Data.Comparison
      - Data.SameItem
      - Data.HasNewValue
      - Data.Streamable
      - Data.Injection
      - Data.Isomorphism
      - Data.Lens
      - Data.Store
      - Data.SpecialCase.SpecialCase
      - Data.SpecialCase.Applicative
      - Data.SpecialCase.Arrow
      - Data.Coerce.Function
      - Data.PurityFunction
      - Data.Codec
      - Data.KeyedOrder
      - Data.KeyContainer
      - Data.ListSet
      - Data.Merge
      - Data.Tree
      - Data.KindMorphism
      - Data.Recursion.FixBox
      - Data.Recursion.AppRec
      - Data.Serializer
      - Data.Serialize.Has
      - Data.ReadShow
      - Data.Witness.ListVProduct
      - Data.Media
      - Data.Text.Markup
      - Control.Category.Dual
      - Control.Category.Lifted
      - Control.Clock
      - Control.Task
      - Control.Stream.Filter
      - Control.Stream.Sink
      - Control.Stream.Source
      - Control.Stream
      - Control.CallbackLock
      - Control.AsyncRunner
      - Unsafe.Type
      - Unsafe.IO
      - Shapes
      - Shapes.Numeric
      - Shapes.Unsafe
      - Shapes.Test
      - Shapes.Test.Context
    other-modules:
      - Unsafe.Refl
      - Shapes.Import
      - Shapes.Instances

tests:
    test:
        source-dirs: test
        dependencies:
          - base >= 4.16
          - time
          - shapes
        main: Main.hs
        other-modules:
          - AppRec
          - Serializer
          - Task
        ghc-options: -threaded
