_common: !include "../common.yaml"
name: changes-world
version: *changes_version
<<: *author

<<: *language

library:
    source-dirs: lib
    dependencies:
      - shapes
      - base >= 4.12
      - time
      - filepath
      - directory
      - aeson
      - sqlite-simple
      - mime
      - changes-core
    exposed-modules:
      - Changes.World.Clock
      - Changes.World.Anything
      - Changes.World.File
      - Changes.World.FileSystem
      - Changes.World.ReferenceStore
      - Changes.World.Charset
      - Changes.World.MIME
      - Changes.World.JSON
      - Changes.World.SQLite
      - Changes.World.SQLite.Schema
