site_name: Pinafore
plugins:
  - commonmark
markdown_extensions:
  - toc:
      baselevel: 3
  - codehilite
  - markdown_include.include:
      base_path: generated
repo_url: https://github.com/AshleyYakeley/Truth
theme:
  name: readthedocs
  highlightjs: false
extra_css: [extra.css]
