site_name: Pinafore
markdown_extensions:
  - toc:
      baselevel: 4
  - codehilite
  - markdown_include.include:
      base_path: generated
repo_url: https://github.com/AshleyYakeley/Truth
theme: readthedocs
extra_css: [extra.css]
nav:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- Invocation: 'invocation.md'
- Syntax: 'syntax.md'
- Type System: 'type-system.md'
- Types: 'types.md'
- Reference Notation: 'reference-notation.md'
- Predefined Bindings: 'predefined.md'
- Examples:
  - Stopwatch: 'examples/stopwatch.md'
  - Calendar: 'examples/calendar.md'
  - People: 'examples/people.md'
  - Events: 'examples/events.md'
- Future Plans: 'future-plans.md'
