site_name: Pinafore
markdown_extensions:
  - toc:
      baselevel: 4
  - codehilite
  - markdown_include.include:
      base_path: generated
repo_url: https://github.com/AshleyYakeley/Truth
theme: readthedocs
extra_css: [extra.css]
nav:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- Invocation: 'invocation.md'
- Future Plans: 'future-plans.md'
- Building: 'building.md'
- Language:
  - Syntax: 'syntax.md'
  - Type System: 'type-system.md'
  - Types: 'types.md'
  - Dynamic Supertypes: 'dynamic-supertypes.md'
  - Reference Notation: 'reference-notation.md'
  - Modules: 'modules.md'
- Library:
  - Std: 'library/Std.md'
  - UI: 'library/UI.md'
  - Debug: 'library/Debug.md'
- Examples:
  - Stopwatch: 'examples/stopwatch.md'
  - Calendar: 'examples/calendar.md'
  - Contacts: 'examples/contacts.md'
  - Events: 'examples/events.md'
