site_name: Pinafore
repo_url: https://github.com/AshleyYakeley/Truth
theme: readthedocs
pages:
- Home: 'index.md'
- Syntax: 'syntax.md'
- Application & Composition: 'application.md'
- Predefined Bindings: 'predefined.md'
