site_name: Pinafore
markdown_extensions:
  - markdown_include.include:
      base_path: generated
repo_url: https://github.com/AshleyYakeley/Truth
theme: readthedocs
extra_css: [extra.css]
nav:
- Home: 'index.md'
- Syntax: 'syntax.md'
- Type System: 'type-system.md'
- Types: 'types.md'
- Reference Notation: 'reference-notation.md'
- Predefined Bindings: 'predefined.md'
