site_name: Pinafore
plugins:
  - commonmark
markdown_extensions:
  - toc:
      baselevel: 3
  - codehilite
  - markdown_include.include:
      base_path: generated
repo_url: https://github.com/AshleyYakeley/Truth
theme:
  name: readthedocs
  highlightjs: false
extra_css: [extra.css]
nav:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- Invocation: 'invocation.md'
- Future Plans: 'future-plans.md'
- Building: 'building.md'
- Language:
  - Syntax: 'syntax.md'
  - Declarations: 'declarations.md'
  - Type System: 'type-system.md'
  - Types: 'types.md'
  - Dynamic Supertypes: 'dynamic-supertypes.md'
  - Do Notation: 'do-notation.md'
  - Applicative Notation: 'applicative-notation.md'
  - Modules: 'modules.md'
- Library:
  - Built In: 'library/pinafore.md'
  - import "pinafore-media": 'library/pinafore-media.md'
  - import "pinafore-gnome": 'library/pinafore-gnome.md'
  - import "UILib": 'library/UILib.md'
- Examples:
  - Stopwatch: 'examples/stopwatch.md'
  - Calendar: 'examples/calendar.md'
  - Contacts: 'examples/contacts.md'
  - Events: 'examples/events.md'
