site_name: Pinafore
repo_url: https://github.com/AshleyYakeley/Truth
theme: readthedocs
pages:
- Home: 'index.md'
- Syntax: 'syntax.md'
- Type System: 'type-system.md'
- Types: 'types.md'
- Predefined Bindings: 'predefined.md'
